name: ContainerizedMetricsGenerator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Navigate to the 'week7' folder
        cd week7
        pip install flake8 pytest
        # Install dependencies from the requirements.txt inside the 'week7' folder if it exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Navigate to the 'week7' folder to run flake8
        cd week7
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        # Navigate to the 'week7' folder to run pytest
        cd week7
        pytest

    - name: Run cli.py
      run: |
        # Navigate to the 'week7' folder and run the cli.py application
        cd week7
        python cli.py
